#!/bin/bash

echo "🔧 Fixing Playwright WSL Setup"
echo "=============================="
echo ""
echo "This script will help you install Playwright dependencies for WSL."
echo ""
echo "Please run the following commands manually:"
echo ""
echo "1. First, clean up any stuck processes:"
echo "   sudo killall -9 apt-get dpkg 2>/dev/null"
echo "   sudo rm -f /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock /var/cache/apt/archives/lock /var/lib/dpkg/lock"
echo ""
echo "2. Then install Playwright dependencies:"
echo "   sudo npx playwright install-deps"
echo ""
echo "3. Finally, install browsers:"
echo "   npx playwright install"
echo ""
echo "After running these commands, you should be able to use 'make test-tdd' successfully."